spring:
  datasource:
    url: jdbc:postgresql://localhost:8090/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: moex
        format_sql: true
        ddl-auto: validate
  logging:
    level:
      org:
        springframework:
          transaction: DEBUG
        hibernate: DEBUG


period:
  days: 182